In [ ]:
import numpy as np

In [ ]:
def create_tiebreakers(n_vals, seed=None, dtype=int):
    np.random.seed(seed)
        
    if dtype is int or dtype is np.array([1]).dtype:
        return np.random.permutation(n_vals)
    elif dtype is float or dtype is np.array([1.0]).dtype:
        return np.random.random(n_vals)
    else:
        raise ValueError('Invalid dtype for create_tiebreakers: {dtype}')

In [ ]:
print(create_tiebreakers(3, seed=1))
print(create_tiebreakers(3, seed=1))
print(create_tiebreakers(4, seed=1))
print(create_tiebreakers(5, seed=1))
print(create_tiebreakers(5, seed=1, dtype=int))
print(create_tiebreakers(3, seed=1, dtype=float))

[0 2 1]
[0 2 1]
[3 2 0 1]
[2 1 4 0 3]
[2 1 4 0 3]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [ ]:
def array1D_to_sorted_indices(array, seed=None, tiebreakers=None, dtype=int):
    '''
    Ties are broken randomly.
    
    If random tie-breaking is not necessary one can use argsort instead.
    
    
    RETURNS
    --------
    array_augments (np.ndarray): 3 col array where first col are the values in array sorted (least to greatest),
    second col has values used for tie-breaking, and third col has the sorted indices of the original vals. 
    e.g. If each value in the input array corresponds to a cand, then the third col has the ids of the cands ordered from least
    to greatest in terms of those values.
    '''
    np.random.seed(seed)
    if tiebreakers is None:
        tiebreakers = create_tiebreakers(len(array), seed, dtype)
    indices = np.arange(len(array), dtype=dtype)
    array_augmented = np.column_stack((array, tiebreakers, indices))
    sorted_indices = np.lexsort((array_augmented[:, 1], array_augmented[:, 0]))
    return array_augmented[sorted_indices]

In [ ]:
array_augmented = array1D_to_sorted_indices([2,3,1,4,4,4,4,5], seed = 1, 
                                                            tiebreakers = None, dtype=int)
print(array_augmented)

array_augmented = array1D_to_sorted_indices([2,3,1,4,4,4,4,5], seed = 2, 
                                                            tiebreakers = None, dtype=int)
print(array_augmented)

[[1 1 2]
 [2 7 0]
 [3 2 1]
 [4 0 4]
 [4 3 6]
 [4 4 5]
 [4 6 3]
 [5 5 7]]
[[1 6 2]
 [2 4 0]
 [3 1 1]
 [4 2 3]
 [4 3 4]
 [4 5 6]
 [4 7 5]
 [5 0 7]]


In [ ]:
def normalize1D(array):
    total = np.sum(array)
    return array / total

def normalize_rows_2D(array):
    return np.array(list(map(normalize1D,array)))

In [ ]:
normalize2D([[1,2,12,5],[5,4,5,6]])

array([[0.05, 0.1 , 0.6 , 0.25],
       [0.25, 0.2 , 0.25, 0.3 ]])